name: mac_bro_test
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # GetX state management
  get: ^4.6.3
  # rest api
  dio: ^4.0.6
  dio_retry_plus: ^1.0.2
  # retrofit
  retrofit: ^3.0.1+1
  # chuck
  chuck_interceptor: ^1.0.0
  # image svg widget
  flutter_svg: ^1.0.3
  # image cache widget
  cached_network_image: ^3.2.0
  # google translation
  translator: ^0.1.7
  # keyboard dismiss
  keyboard_dismisser: ^3.0.0
  # sms auto fill
  sms_autofill: ^2.2.0
  # swipe to bottom refresh widget
  liquid_pull_to_refresh: ^3.0.1
  # cupertino effect
  bouncing_widget: ^2.0.0
  # search bar widget
  flutter_staggered_grid_view: ^0.6.1
  # internet connect
  connectivity_plus: ^2.3.0
  # hive no sql database
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  # screen_utils
  flutter_screenutil: ^5.5.2
  # platform
  platform: ^3.1.0
  json_annotation:
  equatable:
  carousel_slider: ^4.1.1
  html: ^0.15.0
  shared_preferences: ^2.0.15
  flutter_countdown_timer: ^4.1.0
  mask_text_input_formatter: ^2.3.0
  shimmer: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  hive_generator: ^1.1.2
  build_runner: ^2.1.10
  flutter_lints: ^2.0.1
  freezed_annotation:
  freezed:

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

